### ISSUE TITLE
下载文件403

### ISSUE THREAD

**Issue by DecisionTreee** [chinosk6/umamusume-voice-text-extractor#1]
![image](https://user-images.githubusercontent.com/121787369/210983973-fdb7706f-6f9b-4943-9cd1-5d78610e9593.png)
梯子代理到了，但仍报403
![image](https://user-images.githubusercontent.com/121787369/210984682-50ca9f43-d0cb-4a8a-9153-03a3e32252c9.png)

**Comment by chinosk6** [comment]
说明梯子的ip被ban了，请换一个节点。你可以复制控制台里的网址，然后粘贴到浏览器试试。

**Comment by DecisionTreee** [comment]
![image](https://user-images.githubusercontent.com/121787369/210986759-e2bdf68e-e709-47fa-bd23-62ba4123554e.png)
403

**Comment by DecisionTreee** [comment]
好的可以了感谢
