### ISSUE TITLE
怎么配置GUI环境呀

### ISSUE THREAD

**Issue by leno1a** [chinosk6/umamusume-voice-text-extractor#10]
运行马娘文件夹的bat文件命令终端会报错，感觉前置环境没弄好，NET6和二进制文件都下载了，想了解一下如何配置呢？

**Comment by chinosk6** [comment]
报错内容是？

**Comment by leno1a** [comment]
> 
点击马娘voice文件夹下的run.bat文件，程序打开后马上自行闪退，同时命令终端提示：
sqlite3.OperationalError: unable to open database file
[13092] Failed to execute script 'gui_main' due to unhandled exception!

**Comment by chinosk6** [comment]
进一次游戏就行了，你这是游戏资源没初始化。

**Comment by leno1a** [comment]
> 进一次游戏就行了，你这是游戏资源没初始化。
初始化后可以正常运行啦，但是不知道是不是提取过程关闭游戏的原因还是没有代理的原因，提取完成后进行下载的部分全程报错（下载失败），大量提示[ERROR] Download failed: Can't download file from https://prd-storage-umamusume.akamaized.net/dl/resources/Generic/LW/LWJC3G5YSMGGFQOPAZI7IT2F4NEZUJNA (HTTP 403)., retry: 1/3

**Comment by chinosk6** [comment]
这个肯定要挂代理

**Comment by leno1a** [comment]
> 你不在日本的话，肯定要挂代理

我用v2掛了全局代理後，網頁可以直接打開github,uma官網，遊戲dmm端（先加速器繞過dmm地域檢測），依旧如上大量报错，uma程序代理我按照示例输入https://+代理+端口，没有成功，为啥呀？

**Comment by chinosk6** [comment]
这我就帮不了你了。没成功就是配置不对，可能是代理地址填错了，也可能是v2的规则没配置对，这就需要你自己找原因了。

**Comment by chinosk6** [comment]
我看你说 `输入https://+代理+端口`。一般都是 `http`，我还没怎么见过有 `https` 的本地代理

**Comment by leno1a** [comment]
我这边使用v2代理输入地址加端口就可以加速了，哎不知道怎么在uma小程序那里输入代理,咱就是说使用v2全局代理完是不是不用在小程序代理呀

**Comment by leno1a** [comment]
代理大概长这样子，这样子可以输入到小程序代理里面嘛

**Comment by chinosk6** [comment]
你看代理软件的日志，有 `prd-storage-umamusume.akamaized.net` 就行。

**Comment by leno1a** [comment]
没这个，日志一点波澜起伏都没有，我的代理与地址分别是（举例）：192.168.111.11,11111，我就在Uma小程序代理处按照示例格式输入http://192.168.111.11:11111，这样子日志没任何反应。此外代理VPN显示了五位数的本地SOCKS和HTTP，请教一下这些需要用上吗？

**Comment by chinosk6** [comment]
`http://127.0.0.1:http代理端口`

**Comment by leno1a** [comment]
按照这个方法输入后，报错更改为（举例）：
[ERROR] Download failed: Failed to parse: http://192.168.111.11:http11111, retry: 3/3
[ERROR] Exception occurred when loading bundle: Failed to parse: http://192.168.111.11:http11111

**Comment by leno1a** [comment]
此时浏览器的GITHUB和CYGAMES官网是能正常加载并且反映在日志上，Uma的代理不行且没有日志

**Comment by chinosk6** [comment]
你加 http 四个字干啥......
你就输 `http://127.0.0.1:11111`
前提是你确定你的端口就是 11111

**Comment by leno1a** [comment]
按照大佬你第二行的输入内容，这个是我最早报错的试法，http://127.0.0.1:11111（示例）确认后开始运行
报错（截取一段）：
[ERROR] Download failed: HTTPSConnectionPool(host='prd-storage-umamusume.akamaized.net', port=443): Max retries exceeded with url: /dl/resources/Generic/2C/2CSROXKCPEU5WUZFCOA2ZAFDEFJQIHJT (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))), retry: 1/3
[ERROR] Download failed: HTTPSConnectionPool(host='prd-storage-umamusume.akamaized.net', port=443): Max retries exceeded with url: /dl/resources/Generic/2C/2CSROXKCPEU5WUZFCOA2ZAFDEFJQIHJT (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))), retry: 2/3
[ERROR] Download failed: HTTPSConnectionPool(host='prd-storage-umamusume.akamaized.net', port=443): Max retries exceeded with url: /dl/resources/Generic/2C/2CSROXKCPEU5WUZFCOA2ZAFDEFJQIHJT (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))), retry: 3/3
[ERROR] Exception occurred when loading bundle: HTTPSConnectionPool(host='prd-storage-umamusume.akamaized.net', port=443): Max retries exceeded with url: /dl/resources/Generic/2C/2CSROXKCPEU5WUZFCOA2ZAFDEFJQIHJT (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by chinosk6** [comment]
Cannot connect to proxy.
你直接截个 v2ray 界面的图吧

**Comment by leno1a** [comment]
![图片](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/134570418/7ced61b7-36ba-4b78-8b01-f4d9faeb4bd3)

**Comment by chinosk6** [comment]
你的 http 代理端口是 10809 呀。你从哪看的 11111(

**Comment by leno1a** [comment]
> 你的 http 代理端口是 10809 呀。你从哪看的 11111(

11111是举例咧，嘿嘿按照刚刚说的，遇到新鲜出炉的报错一个诶
![图片](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/134570418/ca6d10b1-6b36-4657-8048-7f5d5a9a99c0)

**Comment by chinosk6** [comment]
代理地址部分，就写 `127.0.0.1`，别写其它的

**Comment by chinosk6** [comment]
`http://127.0.0.1:10809` 一个字也别改

**Comment by leno1a** [comment]
我试试

**Comment by leno1a** [comment]
![图片](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/134570418/6e22f7ec-5735-488b-b57f-62e7b6023e4e)

**Comment by leno1a** [comment]
满屏红仿佛见到了爱）

**Comment by chinosk6** [comment]
全局代理关掉，换成别的

**Comment by leno1a** [comment]
![图片](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/134570418/830a7bda-7a55-4530-8d17-67fdb7b41d78)
![图片](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/134570418/5086ecab-5d14-406c-bd35-67ec28f139ef)
![图片](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/134570418/1b6575c0-1711-430f-928a-c703c560fb0b)
穷举了一下，路由把全局换成绕过大陆，系统代理由PAC换成不用系统代理，自动配置系统代理，清除系统代理，全部报错如图。其中清除系统代理（图三）日志会有反应，但依旧报错。

**Comment by chinosk6** [comment]
https://github.com/2dust/v2rayN/issues/2065#issuecomment-1143556141

**Comment by leno1a** [comment]
我把V2代理关了之后，Uma代理填http://127.0.0.1:10809，然后注册表小改了一下，居然就可以了（乐），谢谢大佬啦
