### ISSUE TITLE
[Bug] 导出音频爆音

### ISSUE THREAD

**Issue by mlbv** [chinosk6/umamusume-voice-text-extractor#11]
### 混合器
> 很多歌曲能复现这个问题，这里以马儿蹦跳传说为例
- 打开程序图形界面，选择live音乐提取->音乐1001，选中混合器，添加角色1001、1002、1003到3个歌唱位置  
- 点击“开始混合”
- 得到mix_by_parts.wav
此时，将其导入Au或类似的软件查看响度
<details>
<summary>点击查看图片</summary>
<img src="https://img1.imgtp.com/2023/08/19/ex85TTmG.png" >
</details>

- 不难发现，音频出现了明显的爆音问题

### 提取器
> 仅少量歌曲的伴奏会出现这个问题
- 打开程序图形界面，选择live音乐提取->音乐1009，将“Wave参数”中的参数清空  
- 选择“提取BGM”  
- 得到bgm0.wav
导入Au或类似的软件查看响度
<details>
<summary>点击查看图片</summary>
<img src="https://img1.imgtp.com/2023/08/19/AkgKn9M4.png" >
</details>

- 音频在00:15、01:10、01:34处均出现爆音问题

最后，感谢大佬做的提取工具！

**Comment by chinosk6** [comment]
收到，明天有空看看

**Comment by chinosk6** [comment]
已修复此问题，可以拉取最新代码或者前往 [Releases](../releases) 下载~

**Comment by mlbv** [comment]
问题已解决
