### ISSUE TITLE
[Enhancement] 读取live数据不全

### ISSUE THREAD

**Issue by mlbv** [chinosk6/umamusume-voice-text-extractor#12]
有一些live音频文件并没有被读取
### 伴奏缺失
游戏中几乎所有live均有两个伴奏，分别为snd_bgm_live_xxxx_oke_01和snd_bgm_live_xxxx_oke_02  
两者有细微的差别，一般02伴奏含有更少的背景杂音。以1001-马儿蹦跳传说为例，02不含01中的观众欢呼声  
<details>
<summary>单击展开对比图片</summary>
这是01
<img src="https://img1.imgtp.com/2023/08/20/YdpmurFi.png" >
这是02
<img src="https://img1.imgtp.com/2023/08/20/HkC2fjCx.png" >
</details>

本提取器目前仅能提取01音轨
### 缺少的live
- 1052-プロムダンスパート         *仅有伴奏*
- 1080-ドロワダンスパート         *仅有伴奏*
- 9051-【MCパート】笑顏の宝物 -Beyond The Future!

这三个live的共同点是没有图标
### 修改建议
- 提取BGM时生成两个文件，bgm1.wav和bgm2.wav，分别对应snd_bgm_live_xxxx_oke_01和snd_bgm_live_xxxx_oke_02
- 将缺少的live添加至音乐列表
### *其它建议*
- 将默认Wave参数留空，即默认不进行重采样
- 为混合器添加Wave参数选项
- 为Live音乐提取添加多角色提取模式

**Comment by chinosk6** [comment]
- 混合器的 Wave 参数同 Live 提取器的设置。
 - Live 音乐提取的多角色模式，具体是？能详细描述一下吗

**Comment by mlbv** [comment]
<img src="https://img1.imgtp.com/2023/08/20/RlYTnXL5.png" >
大概是这样，选中一个live后可以多选导出的角色

**Comment by chinosk6** [comment]
这样看来，输出不涉及文本格式。直接让提取器选择歌唱角色时支持多选就行了

**Comment by chinosk6** [comment]
这样看来，输出不涉及文本格式。直接让提取器选择歌唱角色时支持多选就行了对吧

**Comment by mlbv** [comment]
对，差不多

**Comment by chinosk6** [comment]
- 已添加缺少的 Live
 - 提取 Live BGM 和混合器现在会同时输出 oke 01、02 两个版本
 - 提取器已支持多选角色

暂时没有发 Release，请拉取最新代码查看~
