### ISSUE TITLE
[Enhancement] 混合器动态响度控制

### ISSUE THREAD

**Issue by mlbv** [chinosk6/umamusume-voice-text-extractor#13]
在混合器中，由于不固定的歌唱角色的数量和静态的响度控制，多个角色同时歌唱的响度远大于单角色  
<details>
<summary>单击展开与游戏原生播放live的对比</summary>
<img src="https://img1.imgtp.com/2023/08/25/hXG8U1a3.png" >  

绿色音轨为混合器导出音轨，角色音量为默认值0.85  
紫色音轨为游戏播放的live  
红框位置为多角色同时歌唱（只标了我能听出来的部分）
</details>

可以发现，在多角色同时歌唱时混合器的响度高出了一大截  
因此，应引入动态响度控制以保证响度的统一
即：
- 在混合时，对角色的声音降低  $10\lg n$  dB，其中  $n$  为同时歌唱的角色数量

**Comment by chinosk6** [comment]
代码已更新~

**Comment by mlbv** [comment]
Solved  
大佬就是厉害，我昨天试了几个小时都没成功
