### ISSUE TITLE
卡死

### ISSUE THREAD

**Issue by DecisionTreee** [chinosk6/umamusume-voice-text-extractor#2]
有时会卡死，只显示
WARNING] xxx not found, try download...
等了半个小时没有反应
![image](https://user-images.githubusercontent.com/121787369/212533989-c9860fdd-9c8f-4b11-8328-87b1f83a2387.png)

**Comment by DecisionTreee** [comment]
有时候重启梯子可以解决一会然后又开始卡，是梯子的问题吗

**Comment by chinosk6** [comment]
这个明显是你网络卡了，建议换个节点(

**Comment by chinosk6** [comment]
或者我可以加个timeout，让你下载失败的时候不会一直卡着

**Comment by DecisionTreee** [comment]
麻烦了

**Comment by chinosk6** [comment]
已更新
