### ISSUE TITLE
ThrowOverflowOrFormatException

### ISSUE THREAD

**Issue by DecisionTreee** [chinosk6/umamusume-voice-text-extractor#3]
很抱歉再次打扰你
![image](https://user-images.githubusercontent.com/121787369/214238258-a0624704-69f8-4837-92d4-9cce736b04e7.png)
我在使用时报了onvert cueid failed: xxx - System.FormatException: Input string was not in a correct format.的错误
可能是cueidStr转换为int类型时出错
这是否影响数据的提取（提取出来是否是全的？

**Comment by chinosk6** [comment]
再次确认了一下，这部分为差分语音，缺少这部分语音不会对提取完整性造成影响，之后会关掉这条报错的log输出。

**Comment by DecisionTreee** [comment]
好的
