### ISSUE TITLE
无法启动gui

### ISSUE THREAD

**Issue by nikoharo** [chinosk6/umamusume-voice-text-extractor#4]
![aaaasd](https://user-images.githubusercontent.com/96216203/221390648-012bf07a-5ea6-489a-b20a-247e1184457e.png)
报错:[12172] Failed to execute script 'gui_main' due to unhandled exception!

**Comment by chinosk6** [comment]
`unable to open database file`
先把游戏打开，资源下好再开脚本

**Comment by nikoharo** [comment]
游戏数据路径能改吗，我c盘空间不够了

**Comment by chinosk6** [comment]
> 游戏数据路径能改吗，我c盘空间不够了

`mklink /J`

**Comment by nikoharo** [comment]
> > 游戏数据路径能改吗，我c盘空间不够了
> 
> `mklink /J`

加在run.bat里面吗

**Comment by nikoharo** [comment]
我这边提取帝宝音频就217个音频，照理说有600百条以上吧？

**Comment by mangran233** [comment]
打开游戏了以后还是报错
![image](https://user-images.githubusercontent.com/126641366/222042480-86a8a8ca-ecd7-4b8c-9963-c70785a5f4a4.png)

**Comment by chinosk6** [comment]
你没有装 .net 运行时

**Comment by mangran233** [comment]
> 

谢谢，解决了
