### ISSUE TITLE
无法下载缺失的live音乐数据

### ISSUE THREAD

**Issue by Summ3rM0** [chinosk6/umamusume-voice-text-extractor#5]
在gui中的live音乐提取界面勾选下载缺失的文件不起效果，在角色语音提取处正常工作。勾选下载缺失的文件后选择提取BGM，控制台中没有相关下载输出，只会输出System.IO.FileNotFoundException: File not found

**Comment by chinosk6** [comment]
能截图看看具体是哪个文件吗

**Comment by Summ3rM0** [comment]
提取所有未在游戏中下载过的live文件都会输出这个提示
![捕获](https://user-images.githubusercontent.com/106458433/222957497-c4d061bc-a03d-4539-a2f1-e691cee99fa0.PNG)

**Comment by Summ3rM0** [comment]
我猜测这是由于忘记调用下载部分的函数导致的，因为不论是否勾选下载缺失文件，控制台都没有输出任何有关下载的语句

**Comment by chinosk6** [comment]
刚刚提交了commit, 应该修复了。我本体文件是全的, 没法测试(

**Comment by Summ3rM0** [comment]
好的 感谢 我去测试一下

**Comment by Summ3rM0** [comment]
似乎还是有些问题 下载完缺失数据之后还是会报not found
![捕获](https://user-images.githubusercontent.com/106458433/222964645-642664b0-9a2e-4679-9f9c-f0eb268152f0.PNG)

**Comment by chinosk6** [comment]
感谢反馈, 已推送commit, 麻烦再测试一下~

**Comment by Summ3rM0** [comment]
问题解决

**Comment by chinosk6** [comment]
感谢反馈，如果之后出现同样的问题请 Reopen 这个 issue~

**Comment by COMINCWOW** [comment]
同样出现综上所述问题。
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "gui\guimain.py", line 338, in _
  File "voiceex\live_music\live_music_ex.py", line 124, in cut_live_chara_song_by_lrc
  File "voiceex\live_music\live_music_ex.py", line 62, in get_lrc
KeyError: 'time'

**Comment by chinosk6** [comment]
> 同样出现综上所述问题。 Exception in thread Thread-1: Traceback (most recent call last): File "threading.py", line 932, in _bootstrap_inner File "threading.py", line 870, in run File "gui\guimain.py", line 338, in _ File "voiceex\live_music\live_music_ex.py", line 124, in cut_live_chara_song_by_lrc File "voiceex\live_music\live_music_ex.py", line 62, in get_lrc KeyError: 'time'

建议单独开一个 issue 并详细说明一下操作过程，方便复现
