### ISSUE TITLE
A character extraction error after a new character update a while ago

### ISSUE THREAD

**Issue by 9oodra** [chinosk6/umamusume-voice-text-extractor#9]
After Hishi Miracle character update, only the voice of this character is not extracted. am i the problem? I would appreciate it if you could let me know.

cmd text ↓↓↓
![image](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/88673195/e555aa84-0550-49a6-ae16-534d20f9c3f8)

**Comment by chinosk6** [comment]
Fixed [v2.3](../releases/tag/v2.3). Thanks for reporting.
